### ISSUE TITLE
The new context menu settings do not work

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#86]
**Describe the bug**
Excellent idea to add the settings button. However after using that I do not see any options added to the context menu

**To Reproduce**
Click on the More button
Select Settings
Select Context Menu
Select all the possible options or just some 
Click OK and restart OneNote

**Expected behavior**
Selected options should be available when I right click on the page
**Screenshots**
Nothing new is displayed there, the old options that used to be there added by OneMore, are alos gone

**Environment (if applicable):**
OneNote 2013 32b OneMore 3.6

**Comment by stevencohn** [comment]
Sorry you're having problems with this. I can't seem to break it so I'm not sure how to reproduce it. Check the %appdata%\OneMore\Settings.xml file and make sure there are entries under a ContextMenuSheet element, for example

```
  <ContextMenuSheet>
    <ribNoSpellCheckButton>true</ribNoSpellCheckButton>
    <ribPasteRtfButton>true</ribPasteRtfButton>
    <ribHighlightButton>true</ribHighlightButton>
  </ContextMenuSheet>
```

Also check the log file and make sure there are no exception in there after clicking the Settings dialog OK button.

**Comment by 1001QAdotNET** [comment]
yeah they are there

  <?xml version="1.0" encoding="utf-8"?>
<settings>
  <images width="500" />
  <runPlugin>
    <cmd>C:\Utils\WPy64-3771\python-3.7.7.amd64\python.exe</cmd>
    <args>E:\VSCode\onenote-python-plugin\test.py</args>
    <update>false</update>
    <child>true</child>
  </runPlugin>
  <outline>
    <addNumbering>false</addNumbering>
    <alphaNumbering>false</alphaNumbering>
    <numericNumbering>false</numericNumbering>
    <cleanupNumbering>false</cleanupNumbering>
    <indent>false</indent>
    <indentTagged>true</indentTagged>
    <removeTags>true</removeTags>
    <tagSymbol>15</tagSymbol>
  </outline>
  <ContextMenuSheet>
    <ribNoSpellCheckButton>true</ribNoSpellCheckButton>
    <ribPasteRtfButton>true</ribPasteRtfButton>
    <ribEditMenu>true</ribEditMenu>
    <ribHighlightButton>true</ribHighlightButton>
    <ribCleanMenu>true</ribCleanMenu>
    <ribRemoveEmptyButton>true</ribRemoveEmptyButton>
    <ribRemoveSpacingButton>true</ribRemoveSpacingButton>
    <ribTrimButton>true</ribTrimButton>
    <ribUppercaseButton>true</ribUppercaseButton>
    <ribLowercaseButton>true</ribLowercaseButton>
    <ribIncreaseFontSizeButton>true</ribIncreaseFontSizeButton>
    <ribDecreaseFontSizeButton>true</ribDecreaseFontSizeButton>
    <ribRemoveAuthorsButton>true</ribRemoveAuthorsButton>
    <ribRemoveCitationsButton>true</ribRemoveCitationsButton>
    <ribSnippetsMenu>true</ribSnippetsMenu>
  </ContextMenuSheet>
  <HighlightsSheet>
    <theme>Faded</theme>
  </HighlightsSheet>
  <RibbonBarSheet>
    <editCommands>true</editCommands>
    <editIconsOnly>true</editIconsOnly>
    <formulaCommands>true</formulaCommands>
    <formulaIconsOnly>true</formulaIconsOnly>
  </RibbonBarSheet>
  <SearchEngineSheet>
    <engines></engines>
    <engines />
  </SearchEngineSheet>
</settings>

**Comment by 1001QAdotNET** [comment]
I do have some errors in the log


18536:1] Starting dllhost, process PID=18536, CPU=3600Mhz Language=en-US/en-US
18536:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
18536:1] ..OneAddInsUpdate(custom[]:0)
18536:3] ..Error extending context menu
18536:3] ..EXCEPTION - System.NullReferenceException
Message...: Object reference not set to an instance of an object.
StackTrace:    at River.OneMoreAddIn.AddIn.AddContextMenuSearchers(SettingsCollection ccommands, XElement menu)
   at River.OneMoreAddIn.AddIn.GetCustomUI(String RibbonID)
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.AddIn::AddContextMenuSearchers()

**Comment by stevencohn** [comment]
Thanks for that. You always provide enough detail to diagnose the problem :-)

https://github.com/stevencohn/OneMore/releases/tag/3.6.1

**Comment by 1001QAdotNET** [comment]
OK I have tried the new release but that completely wiped out the addon from the ribbon and the quick ribbon 
I had to go back to 3.5  and then back to 3.6 again -so 3.6.1 aggravate the situation

**Comment by stevencohn** [comment]
!!  :-(

And the logs?

**Comment by stevencohn** [comment]
You could try deleting the settings.xml file.

**Comment by stevencohn** [comment]
I grabbed a copy of your Settings.xml file and see there is a problem. I should have done that before.
I'll fix it immediately.

**Comment by stevencohn** [comment]
Fixed https://github.com/stevencohn/OneMore/releases/tag/3.6.2

So sorry about the poor testing before. I've tested it with your Settings.xml file and a few other scenarios and it seems to work fine now.

**Comment by 1001QAdotNET** [comment]
I am seeing a duplication here, is that by design ?
![image](https://user-images.githubusercontent.com/17384308/98117619-098bd580-1e78-11eb-9609-aecb2e7fb89d.png)

**Comment by 1001QAdotNET** [comment]
Oh and although I selected that I do not want to see To UpperCase and To Lowercase they still show up

**Comment by 1001QAdotNET** [comment]
Neah ignore the above I forgot to restart
I think a warning or a reminder is needed as you exit the Settings dialog

**Comment by stevencohn** [comment]
Excellent!
Yes, that's by design. I'll have to explain this a little more in the help... If you choose a menu then that menu and all subitems are added. If you choose one or more subitems then those are added as top-level items in the context menu. So yes, that's why you are seeing duplicates.

If you want subitems like To UPPERCASE as a top-level item and don't care about the other then do not choose the "menu" option. 

If you want only the menu and its subitems but not top-level items then choose only the "menu" item but not the subitems

Yes, I'll add a warning to the dialog. Thanks

**Comment by stevencohn** [comment]
It was a quick and dirty UI, I admit. I could have built something fancier but but it gets the job done and shouldn't be used all that much after you first set it up anyway

**Comment by 1001QAdotNET** [comment]
OK got it 
Works well focus on adding more features -do the fancy things like organizing the UI when nothing else is left or when it is really bothering everybody
Thanks for all these quick releases!
